[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "complex-translator"
version = "0.1.0"
description = "A Python package for complex translation"
authors = [{name = "dnyanmudugar", email = "dnyan.mudugar@yahoo.com"}]
requires-python = ">=3.8"
dependencies = [
    "tokenizer",
    "torch",
    "pandas",
    "requests",
]

[project.optional-dependencies]
dev = ["pytest"]