[build-system]
requires = ["setuptools>=61.0", "wheel"] # <-- Install these packages!
build-backend = "setuptools.build_meta"

[project]
name = "complex-translator"
version = "0.1.1"
description = "A complex translator package"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "Dnyan Mudugar", email = "dnyan.mudugar@yahoo.com"},
]
dependencies = [
    "transformers",
    "torch",
    "pandas",
    "pytest",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
]

[tool.hatch.build.targets.wheel]
packages = ["complex_translator"]