[build-system]
[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "complex-translator"
version = "1.0.0"
description = "A complex Neural Network Machine Translation Package built from scratch"
authors = [
    { name = "dnyanmudugar" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
requires-python = ">=3.8"
dependencies = [
    "torch>=2.0.0",
]

[tool.setuptools.packages.find]
where = ["src"]
