[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "complex-translator"      # The name users will use: 'pip install complex-translator'
version = "0.1.0"
authors = [
  { name="dnyanmudugar", email="dnyan.mudugar@yahoo.com" },
]
description = "A custom neural machine translation package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "torch>=2.0.0",               # Add any external pip packages your code depends on
]

[tool.setuptools.packages.find]
where = ["src"]                  # Tells pip to look inside the 'src' folder
