name: Deploy Pipeline Trigger

on:
  push:
    branches: [main, master]
    tags: ['v*', '[0-9]*']
  workflow_dispatch: # Allows manual triggering from the UI or CLI

jobs:
  trigger_production:
    # Connects directly to your production backend file
    uses: ./.github/workflows/production.yml
